((version 3) (backend cc) (source_digest 3a961926b04eedf5503cba3b73c68645)
 (saved ())
 (segments
  ((8e4c9102b0daee0a7082d679c2fe8bc7
    ((Split (axis (Base 0)) (factor 8) (outer Serial) (inner Serial))
     (Split (axis (Base 1)) (factor 8) (outer Serial) (inner Serial))
     (Split (axis (Base 2)) (factor 8) (outer Serial) (inner Serial))
     (Swap (outer (Minted 0 Split_inner)) (inner (Minted 1 Split_outer)))
     (Swap (outer (Minted 0 Split_inner)) (inner (Minted 1 Split_inner)))
     (Swap (outer (Minted 0 Split_inner)) (inner (Minted 2 Split_outer)))
     (Swap (outer (Minted 0 Split_inner)) (inner (Minted 2 Split_inner)))
     (Swap (outer (Minted 1 Split_inner)) (inner (Minted 2 Split_outer)))
     (Swap (outer (Minted 1 Split_inner)) (inner (Minted 2 Split_inner)))
     (Swap (outer (Minted 1 Split_inner)) (inner (Minted 0 Split_inner)))
     (Stage (source 1)
      (tile_loops ((Minted 0 Split_inner) (Minted 2 Split_inner)))
      (shared false) (cooperative ()) (hoisted false))
     (Stage (source 2)
      (tile_loops ((Minted 2 Split_inner) (Minted 1 Split_inner)))
      (shared false) (cooperative ()) (hoisted false))
     (Privatize (target 0) (over (Minted 2 Split_outer)))))))
 (best_ms 0.000958) (baseline_ms 0.0045))