(* gh-ocannl-871: the shared scan inventory excludes both kinds of non-source file that prompted it:
   checkout metadata, which Dune never declares through [source_tree], and files generated by the
   scan action inside its otherwise-clean sandbox. The space-bearing source pins the reason to walk
   the filesystem rather than encode path boundaries in a manifest. *)

open Base
open Stdio
open Verdict.Claims
module Inventory = Test_utils.Source_inventory

let rec mkdirs path =
  if not (String.equal path Stdlib.Filename.current_dir_name || Stdlib.Sys.file_exists path) then (
    mkdirs (Stdlib.Filename.dirname path);
    try Unix.mkdir path 0o755 with Unix.Unix_error (Unix.EEXIST, _, _) -> ())

let write path =
  mkdirs (Stdlib.Filename.dirname path);
  Out_channel.write_all path ~data:"fixture\n"

let rec remove_tree path =
  match Unix.lstat path with
  | { Unix.st_kind = Unix.S_DIR; _ } ->
      Array.iter (Stdlib.Sys.readdir path) ~f:(fun entry ->
          remove_tree (Stdlib.Filename.concat path entry));
      Unix.rmdir path
  | _ -> Unix.unlink path
  | exception Unix.Unix_error _ -> ()

let () =
  let root = Stdlib.Filename.temp_dir "source inventory " " sandbox" in
  Exn.protect
    ~f:(fun () ->
      let source_a = "src/alpha.ml" in
      let source_b = "path with spaces/beta.py" in
      let generated = "test/operations/scan.actual" in
      let git_metadata = ".git/objects/fixture" in
      List.iter [ source_a; source_b; generated; git_metadata ] ~f:(fun path ->
          write (Stdlib.Filename.concat root path));
      let inventory =
        Inventory.of_dune_sandbox ~workspace_root:root
          ~generated:[ Stdlib.Filename.concat root generated ]
      in
      let paths =
        Inventory.files inventory |> List.map ~f:(fun (file : Inventory.file) -> file.path)
      in
      p "the inventory keeps exact boundaries for every declared source path"
        (List.equal String.equal paths [ source_b; source_a ]);
      p "a generated sandbox occupant is absent from source membership"
        (not (Inventory.mem inventory generated));
      p "Git metadata is absent from source membership" (not (Inventory.mem inventory git_metadata)))
    ~finally:(fun () -> remove_tree root)
